Use of opensource modules
adrianbahja01/terraform-in-21-days pull request #15
Opened 2023-06-26 15:34 UTC by adrianbahja01

2023-06-26 18:33 UTC, vladimirmukhin requested changes

2023-06-26 18:33 UTC, vladimirmukhin commented on level2/loadbalancer.tf
> +    },
You don't need port 80 on your load balancer security group.

2023-06-27 04:59 UTC, adrianbahja01 commented on level2/loadbalancer.tf
> +    },
but I have listener on 80 which redirects to 443/https. Shouldn't I keep 80 on security group too?

2023-06-28 11:21 UTC, geoffrey1330 approved these changes

2023-06-28 11:23 UTC, merged